version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: UTC
  open-pull-requests-limit: 10
  labels:
  - dependencies
  groups:
    python-minor-and-patch:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 06:00
    timezone: UTC
  open-pull-requests-limit: 5
  labels:
  - dependencies
- package-ecosystem: pre-commit
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: Asia/Kolkata
  labels:
  - dependencies
  - pre-commit
  commit-message:
    prefix: chore(deps)
    include: scope
- package-ecosystem: docker
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: 09:00
    timezone: Asia/Kolkata
  labels:
  - dependencies
  - docker
  commit-message:
    prefix: chore(deps)
    include: scope
