"""Similar-transaction retrieval (Phase B.1) — unit + quality tests.

The quality claim is concrete and checkable: a transaction generated by a
specific fraud archetype should retrieve neighbors predominantly from the same
archetype, because the feature space (strictly backward-looking features,
L2-normalized) is what the generator's fraud patterns shape. We assert it on a
hermetic generated ledger, never on guessed numbers.
"""

import numpy as np
import pandas as pd
import pytest
import yaml

from finance_agent.retrieval import (
    SimilarTransactionIndex,
    build_embeddings,
    nearest_neighbors,
    neighbor_rows,
)


@pytest.fixture()
def env(tmp_path):
    """Hermetic generated ledger + config (mirrors tests/test_tools.py)."""
    from generate_data import generate

    df = generate(
        days=90,
        seed=11,
        user="U_Alex",
        n_background_accounts=60,
        start_date="2025-01-01",
    )
    data_path = tmp_path / "transactions.csv"
    df.to_csv(data_path, index=False)
    cfg = {
        "data": {"path": str(data_path)},
        "model_bench": {"bundle_path": str(tmp_path / "missing.joblib")},
        "risk": {
            "blend": {"rules": 0.4, "supervised": 0.3, "isolation_forest": 0.3},
            "fraud_threshold": 0.7,
        },
        "features": {"faiss_retrieval": True},
        "agent": {
            "activity_log": str(tmp_path / "activity.jsonl"),
            "model": "claude-sonnet-4-5",
        },
    }
    cfg_path = tmp_path / "config.yaml"
    with open(cfg_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(cfg, fh, sort_keys=False)
    return {"cfg_path": str(cfg_path), "tmp": tmp_path, "df": df}


def _index(df: pd.DataFrame):
    from finance_agent.features import build_features

    features = build_features(df)
    sorted_positions = df.sort_values("step").index
    meta = df.loc[sorted_positions].copy()
    meta["transaction_id"] = np.asarray(sorted_positions, dtype=int)
    index = SimilarTransactionIndex(build_embeddings(features), meta)
    return index, sorted_positions


# ------------------------------------------------------------------- unit
def test_build_embeddings_l2_normalizes_rows():
    feats = pd.DataFrame({"a": [1.0, 0.0, 3.0], "b": [1.0, 0.0, 4.0], "c": [1.0, 2.0, 0.0]})
    emb = build_embeddings(feats)
    norms = np.linalg.norm(emb, axis=1)
    assert np.allclose(norms, 1.0)  # every row on the unit sphere
    assert emb.shape == feats.shape


def test_index_backend_is_faiss_or_numpy(env):
    index, _ = _index(env["df"])
    assert index.backend() in {"faiss", "numpy"}


def test_find_similar_excludes_the_query_itself(env):
    index, positions = _index(env["df"])
    pos = 5
    tid = int(positions[pos])
    hits = index.find_similar(index.embeddings[pos : pos + 1], k=5, exclude=tid)
    ids = [h["transaction_id"] for h in hits]
    assert tid not in ids
    assert len(ids) == 5


def test_nearest_neighbors_out_of_range_raises(env):
    df = env["df"]
    from finance_agent.features import build_features

    features = build_features(df)
    sorted_positions = df.sort_values("step").index
    meta = df.loc[sorted_positions].copy()
    meta["transaction_id"] = np.asarray(sorted_positions, dtype=int)
    with pytest.raises(IndexError):
        nearest_neighbors(features, meta, transaction_id=len(df) + 50, k=3)


def test_neighbor_rows_trims_and_labels():
    rows = [
        {
            "transaction_id": 7,
            "distance": 0.04,
            "date": "2025-01-01",
            "merchant": "WireOut",
            "amount": np.float64(999.5),
            "fraud_archetype": np.str_("balance_drain"),
            "isFraud": 1,
        },
        {
            "transaction_id": 8,
            "distance": 0.09,
            "date": "2025-01-02",
            "merchant": "Acme Corp Payroll",
            "amount": 123.0,
            "fraud_archetype": "",
            "isFraud": 0,
        },
    ]
    out = neighbor_rows(rows)
    assert out[0]["fraud_archetype"] == "balance_drain"
    assert out[1]["fraud_archetype"] == "legitimate"  # empty archetype -> label
    assert isinstance(out[0]["amount"], float)
    assert set(out[0]) <= {
        "transaction_id",
        "distance",
        "date",
        "merchant",
        "amount",
        "isFraud",
        "fraud_archetype",
    }


def test_neighbor_rows_nan_archetype_becomes_legitimate():
    """Regression: NaN archetypes must map to 'legitimate'.

    float('nan') is *truthy*, so a plain falsy check lets it through — the
    neighbor would surface as 'nan' and the UI would style it as fraud and
    count it in the known-fraud total. Found by the browser-verification run.
    """
    rows = [
        {
            "transaction_id": 9,
            "distance": 0.01,
            "date": "2025-01-03",
            "merchant": "M_Cafe",
            "amount": 12.5,
            "fraud_archetype": float("nan"),
            "isFraud": 0,
        },
        {
            "transaction_id": 10,
            "distance": 0.02,
            "date": "2025-01-04",
            "merchant": "M_Shop",
            "amount": 44.0,
            "fraud_archetype": None,
            "isFraud": 0,
        },
    ]
    out = neighbor_rows(rows)
    assert out[0]["fraud_archetype"] == "legitimate"
    assert out[1]["fraud_archetype"] == "legitimate"


# ----------------------------------------------------------- tool integration
def test_find_similar_transactions_tool_payload(env):
    from finance_agent.tools import FinanceFacts

    facts = FinanceFacts(env["cfg_path"])
    fraud = env["df"][env["df"]["isFraud"] == 1]
    assert not fraud.empty, "fixture must contain fraud rows"
    tid = int(fraud.index[0])
    result = facts.find_similar_transactions(transaction_id=tid, k=5)
    data = result["data"]
    assert data["enabled"] is True
    assert data["transaction_id"] == tid
    assert len(data["neighbors"]) == 5
    assert {"transaction_id", "distance", "fraud_archetype"} <= set(data["neighbors"][0])
    # the query row itself is described in the payload
    assert "query" in data and "merchant" in data["query"]
    assert result["summary"]


def test_find_similar_defaults_to_top_risk_transaction(env):
    from finance_agent.tools import FinanceFacts

    facts = FinanceFacts(env["cfg_path"])
    result = facts.find_similar_transactions(k=3)
    assert result["data"]["enabled"] is True
    assert len(result["data"]["neighbors"]) == 3


def test_find_similar_unknown_id_returns_clean_error(env):
    from finance_agent.tools import FinanceFacts

    facts = FinanceFacts(env["cfg_path"])
    result = facts.find_similar_transactions(transaction_id=999_999, k=3)
    assert result["data"]["neighbors"] == []
    assert "no transaction" in result["summary"].lower()


def test_feature_flag_disables_retrieval(env):
    from finance_agent.tools import FinanceFacts

    cfg_path = env["tmp"] / "disabled.yaml"
    import shutil

    shutil.copy(env["cfg_path"], cfg_path)
    with open(cfg_path, encoding="utf-8") as fh:
        cfg = yaml.safe_load(fh)
    cfg["features"] = {"faiss_retrieval": False}
    with open(cfg_path, "w", encoding="utf-8") as fh:
        yaml.safe_dump(cfg, fh, sort_keys=False)
    facts = FinanceFacts(str(cfg_path))
    result = facts.find_similar_transactions(k=3)
    assert result["data"]["enabled"] is False
    assert result["data"]["neighbors"] == []


# ------------------------------------------------------ the quality claim (B.1)
@pytest.mark.parametrize("k", [5, 10])
def test_archetype_purity_fraud_neighbors_cluster(env, k):
    """Phase B.1 acceptance: a fraud archetype's transactions retrieve
    neighbors predominantly from the same archetype.

    Measured on the fraud-labeled rows of the returned neighborhood: the
    majority of fraud neighbors must share the query row's archetype, and the
    nearest fraud neighbor must share it too (the strongest form of the
    claim). Legitimate rows in the neighborhood are expected (fraud is ~1% of
    the ledger) and don't count against purity.
    """
    df = env["df"]
    fraud = df[df["isFraud"] == 1]
    counts = fraud["fraud_archetype"].value_counts()
    archetypes = [a for a, n in counts.items() if n >= 4]
    assert archetypes, "fixture should carry several archetypes with support >= 4"

    index, positions = _index(df)
    pos_by_tid = {int(t): int(i) for i, t in enumerate(positions)}

    all_frac: list[float] = []
    nearest_ok = 0
    queries = 0
    for arch in archetypes:
        rows = fraud[fraud["fraud_archetype"] == arch].index
        for tid in rows[:2]:  # up to two queries per archetype
            if tid not in pos_by_tid:
                continue
            pos = pos_by_tid[tid]
            hits = index.find_similar(index.embeddings[pos : pos + 1], k=k, exclude=int(tid))
            fraud_n = [h for h in hits if h.get("fraud_archetype")]
            if not fraud_n:
                continue  # no fraud neighbors in range — nothing to measure
            queries += 1
            frac = sum(1 for h in fraud_n if h["fraud_archetype"] == arch) / len(fraud_n)
            all_frac.append(frac)
            nearest_ok += int(fraud_n[0]["fraud_archetype"] == arch)

    assert queries >= 3, "expected at least 3 measurable queries"
    assert np.mean(all_frac) >= 0.5, (
        f"same-archetype fraction among fraud neighbors too low: "
        f"mean {np.mean(all_frac):.2f} over {queries} queries"
    )
    assert nearest_ok / queries >= 0.6, (
        f"nearest fraud neighbor shares the archetype only {nearest_ok}/{queries} times"
    )
